name = "PandaModels"
uuid = "2dbab86a-7cbf-476f-9afe-75ffd3079e7c"
authors = ["e2nIEE"]
version = "0.1.0"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"

[compat]
Cbc = "0.8, 0.9"
InfrastructureModels = "0.6"
Ipopt = "0.7, 0.8"
JSON = "0.21"
JuMP = "0.21"
Juniper = "0.7"
Memento = "1"
PowerModels = "0.18"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
